### ISSUE TITLE
Need help with "Enable CasePathMacros. We are using SwiftUI Navigation for the demo which requires this."

### ISSUE THREAD

**Issue by kemalcany** [powersync-ja/powersync-kotlin-swift-demo#16]
Can someone help with how to do this on Xcode? Thank you!

**Comment by kemalcany** [comment]
Sorry, Xcode noob here. Please ignore..

**Comment by DominicGBauer** [comment]
Hi @kemalcany glad you found it, please let us know if you need any further assistance. We are quite active on Discord if you would like another way to get support https://discord.gg/powersync
